version: '3.8'
services:
    db:
        image: 'postgres:13.8'
        ports:
            - '5432:5432'
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=qwerty
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=db-dev
